language: android
jdk: oraclejdk8
# this part installs dependencies of node.js and react-native
# before_install:
# - nvm install 6
# - node --version
# install:
# - npm install
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
script: 
# here should be some code to test js, e.g. "npm test"using Jest
# for now we are not familiar with Jest, so just skip this step
# SO THERE'S NO TEST FOR JS
- cd android && ./gradlew assembleRelease
